export const ADD_TODO = 'ADD_TODO'
export const INIT_TODOS = 'INIT_TODOS'
export const UPDATE_TODO = 'UPDATE_TODO'
export const EDITING_TODO = 'EDITING_TODO'
export const SYNC_UPDATE_TODO_SUCCESS = 'SYNC_UPDATE_TODO_SUCCESS'
export const SYNC_UPDATE_TODO_ERROR = 'SYNC_UPDATE_TODO_ERROR'

export const ADD_GTD = 'ADD_GTD'
export const INIT_GTD = 'INIT_GTD'
export const UPDATE_GTD = 'UPDATE_GTD'

export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS'
export const VERIFY_USER_FAILURE = 'VERIFY_USER_FAILURE'

export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'
export const FETCH_GTD_SUCCESS = 'FETCH_GTD_SUCCESS'

export const HAS_READ_USER_ERROR = 'HAS_READ_USER_ERROR'
